### ISSUE TITLE
Please disable the stupid gcc wrapper

### ISSUE THREAD

**Issue by adam900710** [radxa/kernel#44]
The wrapper introduced in commit c2482146d144 (rk: Makefile: add gcc-wrapper) is a poor man's -Werror build config.

While the RK guys choose not to backport the proper config for it, they introduced their own wrapper for it.

The damn wrapper can not even handle the latest toolchain, as all the newer warnings would just be treated as error and fail the build.

If RK guys are not able to do proper backports, please don't be creative on causing new bugs.

**Comment by RadxaYuntian** [comment]
You are venting at the wrong place. We merely use what Rockchip provided to us, and can't control how many hacks they want to implement.

If you are having issue building the code, you can try building the kernel with our [`bsp`](https://github.com/radxa-repo/bsp) tool, which (until recently) contains the necessary patches to build under Arch with the latest toolchain. The tool now switched to build in Docker by default since we now force host tools to be built in aarch64 to have correct `linux-headers` package.

You can do `./bsp linux rockchip` to build this fork. Require docker, binfmt_misc and qemu-user-static installed on the host system.

**Comment by adam900710** [comment]
OK, Rockchip sh*t never changes.

For BSP, does it support aarch64 native build? Aka, build the whole thing under aarch64 environment (with distcc for help though)

**Comment by RadxaYuntian** [comment]
Currently all our developments are done on x86_64 system so this is not tested. You can try building with `-n` flag which disables Docker.

**Comment by adam900710** [comment]
All right.

I can already build the vendor kernel after reverting that wrapper commit natively on aarch64 with ArchlinuxARM already.
I guess it should be possible to use `dsp` tool to build the kernel at least.
