### ISSUE TITLE
Rock 5*A*  fan pwm

### ISSUE THREAD

**Issue by Rippanda12** [radxa/kernel#88]
Hello on rock 5B fan pwm is `/sys/devices/platform/fd8b0010.pwm` 
looking using `ls /sys/devices/platform/*pwm*` results in nothing

**Comment by CodeChenL** [comment]
try`/sys/class/pwm`

**Comment by RadxaYuntian** [comment]
Fan support has been added in the following commit: https://github.com/radxa/kernel/commit/d3e9cd5cda3ac169c663682f29af1e688519798c.

**Comment by Rippanda12** [comment]
Doesn't work the fan doesnt spin up (the chip almost throthles 70C)
![image](https://user-images.githubusercontent.com/59401553/231995232-a41aa0f5-9298-480a-89d7-444d1d8a3775.png)
![image](https://user-images.githubusercontent.com/59401553/231995866-1893edec-5f0b-4688-9263-c6d76c18507b.png)
meanwhile on rock 5B theres a pwm* folder which allows the controll
![image](https://user-images.githubusercontent.com/59401553/231996693-29d5493f-4dfc-485f-8a6e-be6ea0b559da.png)

**Comment by RadxaYuntian** [comment]
Once the PWM signal is registered as `pwm-fan` it cannot be accessed by standard PWM interface since it is now part of thermal subsystem. You should [set thermal governors](https://github.com/radxa-pkg/rsetup/blob/main/src/usr/lib/rsetup/cli/system.sh#L85-L89) to [`step_wise`](https://github.com/radxa-pkg/rsetup/blob/main/src/usr/lib/rsetup/tui/hardware/hardware.sh#L97) so the fan can be controlled according to the [temperature targets](https://github.com/radxa/kernel/commit/d3e9cd5cda3ac169c663682f29af1e688519798c#diff-ca6356fe35b0685a8e7d552cc799f6cbbf3b5211113571edbb6128f749a67372R702-R722).

**Comment by Rippanda12** [comment]
then why isnt the same done for rock 5b?

**Comment by RadxaYuntian** [comment]
This is part of the requirement for our new systems, that all PWM fan has to be properly registered as thermal cooling devices. 5B's system was created before this change, so it will be updated later. We expect to release new 5B image along with 5A.
